### PR TITLE
usbd ack SET_INTERFACE if it is not implemented by class driver.

### PR DESCRIPTION
**Pull request by ghost**
**Describe the PR**
This pull request solves a problem with WebUSB on Linux and probably also Mac OS. Without this patch trying to use WebUSB ends in error messages "NetworkError: Unable to set device interface."

This patch is not from me (correct author has been added) and originates from: https://github.com/hathach/tinyusb/pull/711

I've tested the patch and with it applied, I can use the RPi Pico with WebUSB on Linux.

### CODE REVIEW

**Comment by lurch** [comment]
Is this fix already included in tinyusb 0.9.0 ? See https://github.com/raspberrypi/pico-sdk/pull/321

**Comment by ghost** [comment]
It is. So it depends on when you want to merge the new version. If it takes longer it may be helpful if you merge this smaller change in the mean time.

**Comment by lurch** [comment]
That's entirely a @kilograham decision.

**Comment by kilograham** [comment]
i mean i could merge it, but the sdk tinyusb submodule ref isn't going to get bumped until the next release which will pick up 0.9.0 anyway. It should be in under 2 weeks

**Comment by lurch** [comment]
I guess this can be closed, now that 0.10.1 has been merged in?

**Pull request closed without merging**
